@startuml
!include style.puml
skinparam ArrowFontStyle plain

Actor user as user USER_COLOR

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as Logic LOGIC_COLOR
participant ":AddOrderCommand" as AddOrderCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
participant "order:Order" as Order MODEL_COLOR
end box

box UI UI_COLOR_T1
participant "OrderListPanel" as OrderListPanel UI_COLOR
end box

user -[USER_COLOR]> Logic : add order command
activate Logic LOGIC_COLOR

Logic -[LOGIC_COLOR]> AddOrderCommand : execute
activate AddOrderCommand LOGIC_COLOR

AddOrderCommand -[LOGIC_COLOR]> AddOrderCommand : getValidClient(model)
activate AddOrderCommand LOGIC_COLOR_T1
AddOrderCommand -[LOGIC_COLOR]> Model : getFilteredPersonList()
activate Model MODEL_COLOR
Model -[MODEL_COLOR]-> AddOrderCommand : personList
deactivate Model MODEL_COLOR
AddOrderCommand -[LOGIC_COLOR]-> AddOrderCommand : personWhoOrdered
deactivate AddOrderCommand LOGIC_COLOR_T1

ref over AddOrderCommand, Model
  Get valid order items
end ref

create Order MODEL_COLOR
AddOrderCommand -[LOGIC_COLOR]> Order : new Order(personWhoOrdered, orderList)
activate Order MODEL_COLOR
Order -[MODEL_COLOR]-> AddOrderCommand : toAddOrder
deactivate Order MODEL_COLOR

AddOrderCommand -[LOGIC_COLOR]> Model : hasOrder(toAddOrder)
activate Model MODEL_COLOR
Model -[MODEL_COLOR]-> AddOrderCommand : false
deactivate Model MODEL_COLOR

ref over AddOrderCommand, OrderListPanel
  Add order and save to storage
end ref

create CommandResult LOGIC_COLOR
AddOrderCommand -[LOGIC_COLOR]> CommandResult : new CommandResult("New order added: " + order)
activate CommandResult LOGIC_COLOR
CommandResult -[LOGIC_COLOR]-> AddOrderCommand : result
deactivate CommandResult LOGIC_COLOR

AddOrderCommand -[LOGIC_COLOR]-> Logic : result
deactivate AddOrderCommand LOGIC_COLOR

destroy AddOrderCommand
Logic -[LOGIC_COLOR]> : saveAddressBook()
Logic -[LOGIC_COLOR]-> user : result
deactivate Logic LOGIC_COLOR
@enduml
