@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor UI_COLOR_T4
skinparam classBackgroundColor UI_COLOR

package UI <<Rectangle>>{
    Class "<<interface>>\nUi" as Ui
    Class "{abstract}\nUiPart" as UiPart
    Class UiManager
    Class MainWindow
    Class HelpWindow
    Class ResultDisplay
    Class PersonListPanel
    Class PastryListPanel
    Class OrderListPanel
    Class OrderDetailsPanel
    Class PersonCard
    Class PastryCard
    Class OrderCard
    Class StatusBarFooter
    Class CommandBox
}

package Model <<Rectangle>> {
    Class HiddenModel #FFFFFF
}

package Logic <<Rectangle>> {
    Class HiddenLogic #FFFFFF
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Ui

UiManager .up.|> Ui
UiManager -down-> "1" MainWindow

MainWindow *-up->  "1" CommandBox
MainWindow -up-> "0..1" HelpWindow
MainWindow *-up-> "1" ResultDisplay
MainWindow *-up-> "1" StatusBarFooter
MainWindow *-down-> "1" PersonListPanel
MainWindow *-down-> "1" PastryListPanel
MainWindow *-down-> "1" OrderListPanel
MainWindow *-down-> "1" OrderDetailsPanel

PersonListPanel -down-> "*" PersonCard
PastryListPanel -down-> "*" PastryCard
OrderListPanel -down-> "*" OrderCard

' commented out UiPart inheritance for now, for cleaner diagram
' MainWindow -left-|> UiPart
' ResultDisplay --|> UiPart
' CommandBox --|> UiPart
' PersonListPanel --|> UiPart
' PersonCard --|> UiPart
' PastryCard --|> UiPart
' StatusBarFooter --|> UiPart
' HelpWindow --|> UiPart

PersonCard .> Model
PastryCard .> Model
OrderCard .> Model
OrderDetailsPanel -down.> Model
UiManager -right-> Logic
MainWindow -right-> Logic

PersonListPanel -[hidden]left- PastryListPanel
PastryListPanel -[hidden]left- OrderListPanel

PersonCard -[hidden]left- PastryCard
PastryCard -[hidden]left- OrderCard
OrderCard -[hidden]left- OrderDetailsPanel

MainWindow -[hidden]left- CommandBox
CommandBox -[hidden]right- StatusBarFooter
StatusBarFooter -[hidden]right- ResultDisplay
ResultDisplay -[hidden]right- HelpWindow

@enduml
